version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  testing:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deployment:
    executor:
      name:  node/default
    steps:
      - run:
          name: Shell to server
          command: |
            mkdir ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -H 103.74.254.244 >> ~/.ssh/known_hosts
            ssh nc-user@103.74.254.244 ./runner.sh
workflows:
    test-and-deploy:
      jobs:
        - testing
        - deployment:
            requires:
              - testing
